### ISSUE TITLE
The library doesn't work in node's strict mode (--use_strict)

### ISSUE THREAD

**Issue by tsabolov** [kjur/jsrsasign#141]
When running node in strict mode (with a command line argument `--use_strict`) the library fails upon require:
```javascript
const r = require('jsrsasign');
```
```
ReferenceError: KJUR is not defined
    at Object.<anonymous> (/Users/../../../node_modules/jsrsasign/lib/jsrsasign.js:234:41)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
```
[There](https://github.com/kjur/jsrsasign/blob/master/npm/lib/jsrsasign.js#L234) is a check for presence of the global variable KJUR:
```javascript
if (typeof KJUR === 'undefined') { ... }
```
But in strict mode it's prohibited to create, modify and even get value of undeclared global variables.
Please consider to change this behaviour in order to make the library work in strict mode.

**Comment by kjur** [comment]
I've removed unnecessary evals in the latest version 5.0.7 so that jsrsasign works in the strict mode of Node. Thanks.
