### ISSUE TITLE
YAHOO navigator reference error

### ISSUE THREAD

**Issue by zenit1** [kjur/jsrsasign#255]
Hi

On version 7.1.4 I received the following error on require("jsrsasign")

`if(typeof YAHOO=="undefined"||!YAHOO){var YAHOO={};}YAHOO.namespace=function(){var b=arguments,g=null,e,c,f;for(e=0;e<b.length;e=e+1){f=(""+b[e]).split(".");g=YAHOO;for(c=(f[0]=="YAHOO")?1:0;c<f.length;c=c+1){g[f[c]]=g[f[c]]||{};g=g[f[c]];}}return g;};YAHOO.log=function(d,a,c){var b=YAHOO.widget.Logger;if(b&&b.log){return b.log(d,a,c);}else{return false;}};YAHOO.register=function(a,f,e){var k=YAHOO.env.modules,c,j,h,g,d;if(!k[a]){k[a]={versions:[],builds:[]};}c=k[a];j=e.version;h=e.build;g=YAHOO.env.listeners;c.name=a;c.version=j;c.build=h;c.versions.push(j);c.builds.push(h);c.mainClass=f;for(d=0;d<g.length;d=d+1){g[d](c);}if(f){f.VERSION=j;f.BUILD=h;}else{YAHOO.log("mainClass is undefined for module "+a,"warn");}};YAHOO.env=YAHOO.env||{modules:[],listeners:[]};YAHOO.env.getVersion=function(a){return YAHOO.env.modules[a]||null;};YAHOO.env.parseUA=function(d){var e=function(i){var j=0;return parseFloat(i.replace(/\./g,function(){

ReferenceError: navigator is not defined
    at Object.YAHOO.env.parseUA (/Users/zenit1/Projects/SDK/beame-sdk/node_modules/jsrsasign/lib/jsrsasign.js:12:973)
    at Object.<anonymous> (/Users/zenit1/Projects/SDK/beame-sdk/node_modules/jsrsasign/lib/jsrsasign.js:12:2512)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zenit1/Projects/SDK/beame-sdk/tests/serge_local_tests/jsrsasign.js:6:12)`

Version 7.1.3 works fine

Best regards

Serge

**Comment by kjur** [comment]
Thank you for your report. I'll check it later.

**Comment by kjur** [comment]
I've released jsrsasign npm 7.1.15. Thanks.
