### ISSUE TITLE
Getting "ReferenceError: KJUR is not defined" while using Jest in React JS

### ISSUE THREAD

**Issue by vipin001** [kjur/jsrsasign#278]
While running jest i am getting below error
  ● Test suite failed to run

    ReferenceError: KJUR is not defined
      
      at src/lib/SignatureJs/jsencrypt.min.js:41:47
      at Object.<anonymous> (src/lib/SignatureJs/jsencrypt.min.js:74:15949)
      at Object.<anonymous> (src/lib/utility.js:4:18)
      at Object.<anonymous> (src/components/customDOB/customDOB.js:3:16)
      at Object.<anonymous> (src/components/index.js:1:3207)
      at Object.<anonymous> (src/containers/Login/Login.js:5:19)
      at Object.<anonymous> (src/containers/Login/Login.test.js:2:14)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:758:12)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

I have tried "import KJUR from 'jsrsasign'" Still no luck.

**Comment by kjur** [comment]
Sorry but jsrsasign on React JS is NOT supported. Thank you for your understanding.

**Comment by stephenlprice** [comment]
@kjur do you think you can let users know about this in the docs?: https://kjur.github.io/jsrsasign/

I only learned about a lack of support for React after finding this issue.

**Comment by kjur** [comment]
@stephenlprice  I'm not a React programmer. I think it is better to leave it for others to write them.
