### ISSUE TITLE
ReferenceError: alert is not defined

### ISSUE THREAD

**Issue by iSimar** [kjur/jsrsasign#325]
Getting a Error on Node app, with this stack. Shouldn't it be `console.log`?
```
ReferenceError: alert is not defined
    at pkcs1pad2 (_____/node_modules/jsrsasign/lib/jsrsasign.js:220:303)
    at RSAKey.RSAEncrypt [as encrypt] (_____/node_modules/jsrsasign/lib/jsrsasign.js:220:2012)
    at Function.KJUR.crypto.Cipher.encrypt (_____/node_modules/jsrsasign/lib/jsrsasign.js:242:13746)
```

**Comment by kjur** [comment]
Thank you for your report. It is a bug in Tom Wo's RSAKey code. I'll fix it in the next version.

**Comment by kjur** [comment]
8.0.6 released today and this issue was fixed. Thanks.
