### ISSUE TITLE
Problem with verify

### ISSUE THREAD

**Issue by Berkmann18** [kjur/jsrsasign#358]
I'm currently in the process of using this package to implement a PKE signing scheme to a project and got the signing phase to work but when I'm trying to verify the signature with the same parameters it seems to fail when testing with jest.
Here's the code:
```js
const sign = (sk, msg, byteLen = 512) => {
  let sig = new jrs.Signature({alg: `SHA${byteLen}withRSA`});
  sig.init(sk);
  sig.updateString(msg);
  return sig.sign();
};

const vrf = (sk, msg, sig, byteLen = 512) => {
  let tag = new jrs.Signature({alg: `SHA${byteLen}withRSA`});
  tag.init(sk);
  tag.updateString(msg);
  return tag.verify(sig);
};
```
`sk` is generated via KGen function as below:
```js
const genKey = (keyLen = 2048) => {
  let kp = jrs.KEYUTIL.generateKeypair('RSA', keyLen);
  return {pk: kp.pubKeyObj, sk: kp.prvKeyObj}
};
```
Whenever I'm trying to run:
```js
let len = 1024, sk = genKey(len), m = 'Hello', sig = sign(sk, m, len / 2);
vrf(sk, m, sig, len / 2);
```
I get the following error `Signature: unsupported public key alg: rsa`.
Am I missing something?

**Comment by kjur** [comment]
It seems your hash length is too short for the RSA key length.

**Comment by Berkmann18** [comment]
I get the same error using a 2048-bit key with SHA512 (same for 1024-bit / SHA256) which makes sense because the error doesn't mention that problem unlike the other errors I've encountered and solved.

**Comment by kjur** [comment]
How about this?:
```JavaScript
var kp = KEYUTIL.generateKeypair("RSA", 2048);
var prv = kp.prvKeyObj;
var sig = rs.KJUR.crypto.Signature({"alg": "SHA512withRSA"})
sig.init(prv);
var hSigVal = sig.sign();
```

**Comment by Berkmann18** [comment]
That snippet doesn't work, I get this:
```cli
sig.init(prv);
    ^

TypeError: Cannot read property 'init' of undefined
    at Object.<anonymous> (/home/maxie/Dropbox/Projects/NuxCoin/tests/jrs:6:5)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```
Here's the full code based on your snippet:
```js
const rs = require('jsrsasign');

let kp = rs.KEYUTIL.generateKeypair('RSA', 2048);
let prv = kp.prvKeyObj;
let sig = rs.KJUR.crypto.Signature({alg: 'SHA512withRSA'});
sig.init(prv);
let hSigVal = sig.sign();
console.log(hSigVal);
```
Whenever I run  `genKey()` followed by `sign()`, it works but when it comes to verifying the signature using it fails and I can't find something in the API that works so far.

**Comment by kjur** [comment]
It seems you are missing "new":
```JavaScript
function aaa() {
  "use strict";
  const rs = require('jsrsasign');

  let kp = rs.KEYUTIL.generateKeypair('RSA', 2048);
  let prv = kp.prvKeyObj;
  let pub = kp.pubKeyObj;

  let sig = new rs.KJUR.crypto.Signature({alg: 'SHA512withRSA'});
  sig.init(prv);
  sig.updateString("aaa");
  let hSigVal = sig.sign();
  console.log(hSigVal);

  let sig2 = new rs.KJUR.crypto.Signature({alg: 'SHA512withRSA'});
  sig2.init(pub);
  sig2.updateString("aaa");
  let isValid = sig2.verify(hSigVal);
  console.log(isValid);
}
aaa();
```
This works fine.

**Comment by Berkmann18** [comment]
Ha, there we go, it seems to have been a silly mistake regarding the key used for the verification.
My bad!
