### ISSUE TITLE
[x509] RSA-PSS signing fails

### ISSUE THREAD

**Issue by augjoh** [kjur/jsrsasign#447]
Creating an x509 certificate with an RSA-PSS signature fails:

```
(venv) node@nodejs /u/h/node> cat test/x509-PSS.js 
#!/usr/bin/env node

var jsrsasign = require('jsrsasign');

var caKeyPair = jsrsasign.KEYUTIL.generateKeypair('RSA', 1024);
var certKeyPair = jsrsasign.KEYUTIL.generateKeypair('RSA', 1024);

var certPEM = jsrsasign.KJUR.asn1.x509.X509Util.newCertPEM({
  serial: {int: 4},
  sigalg: {name: 'SHA256withRSAandMGF1'},
  issuer: {str: '/C=US/O=a'},
  notbefore: {'str': '130504235959Z'},
  notafter: {'str': '140504235959Z'},
  subject: {str: '/C=US/O=b'},
  sbjpubkey: certKeyPair.pubKeyObj,
  ext: [
    {basicConstraints: {cA: true, critical: true}},
    {keyUsage: {bin: '11'}},
  ],
  cakey: caKeyPair.prvKeyObj
});
```

It looks like an appropiate OID is missing:
```
(venv) node@nodejs /u/h/node> node --trace-uncaught test/x509-PSS.js
[...]
Name of ObjectIdentifier not defined: SHA256withRSAandMGF1
Thrown at:
    at name2obj (/usr/home/node/node_modules/jsrsasign/lib/jsrsasign.js:235:29799)
    at getEncodedHex (/usr/home/node/node_modules/jsrsasign/lib/jsrsasign.js:235:21936)
    at getFreshValueHex (/usr/home/node/node_modules/jsrsasign/lib/jsrsasign.js:233:14130)
    at getEncodedHex (/usr/home/node/node_modules/jsrsasign/lib/jsrsasign.js:233:3949)
    at getEncodedHex (/usr/home/node/node_modules/jsrsasign/lib/jsrsasign.js:235:3465)
    at sign (/usr/home/node/node_modules/jsrsasign/lib/jsrsasign.js:235:572)
    at KJUR.asn1.x509.X509Util.newCertPEM (/usr/home/node/node_modules/jsrsasign/lib/jsrsasign.js:235:31839)
    at /usr/home/node/test/x509-PSS.js:8:49
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

**Comment by kjur** [comment]
Thank you for your report. I'll investigate this.

**Comment by kjur** [comment]
After the investigation, newCertPEM and KJUR.asn1.x509.Certificate don't support RSA-PSS certificate yet. There is no OID for SHA256withRSAandMGF1 in standards. I need to update AlgorithmIdentiifer and Certificate class to support RSA-PSS certificate. It may be implemented in the future. Thank you for your understanding.

**Comment by kjur** [comment]
I've started to add RSA-PSS support for AlgorithmIdentifier, Signature, Certificate and X509Util class. I think it will be provided in the next release.

**Comment by kjur** [comment]
Hi @augjoh , RSA-PSS certificate supported in newCertPEM from jsrsasign 8.0.21 released today.
https://github.com/kjur/jsrsasign/releases/tag/8.0.21
