### ISSUE TITLE
when calling JWS.generateJWSByNED, has no method 'isSafeJSONString'

### ISSUE THREAD

**Issue by hiyosi** [kjur/jsrsasign#50]
when create a signature by RSA-SHA256 algorithm,I have got an error.

It was the message of  "TypeError: Object [object Object] has no method 'isSafeJSONString'"

The following are the steps.

````
$ npm install jsrsasign

$ node

> var r = require('jsrsasign');

> var header = '{"alg":"RS256"}';

> var payload = '{"iss":"joe", "exp":1300819380, "http://example.com/is_root":true}';

> var jwk =   {"kty":"RSA",
    "n":"ofgWCuLjybRlzo0tZWJjNiuSfb4p4fAkd_wWJcyQoTbji9k0l8W26mPddxHmfHQp-Vaw-4qPCJrcS2mJPMEzP1Pt0Bm4d4QlL-yRT-SFd2lZS-pCgNMsD1W_YpRPEwOWvG6b32690r2jZ47soMZo9wGzjb_7OMg0LOL-bSf63kpaSHSXndS5z5rexMdbBYUsLA9e-KXBdQOS-UTo7WTBEMa2R2CapHg665xsmtdVMTBQY4uDZlxvb3qCo5ZwKh9kG4LT6_I5IhlJH7aGhyxXFvUK-DWNmoudF8NAco9_h9iaGNj8q2ethFkMLs91kzk2PAcDTW9gb54h4FRWyuXpoQ",
    "e":"AQAB",
    "d":"Eq5xpGnNCivDflJsRQBXHx1hdR1k6Ulwe2JZD50LpXyWPEAeP88vLNO97IjlA7_GQ5sLKMgvfTeXZx9SE-7YwVol2NXOoAJe46sui395IW_GO-pWJ1O0BkTGoVEn2bKVRUCgu-6f3l9kJfFNS3E0QbVdxzubSu3Mkqzjkn439X0M_V51gfpRLI9JYanrC4D4qAdGcopV_0ZHHzQlBjudU2QvXt4ehNYTCBr6XCLQUShb1juUO1ZdiYoFaFQT5Tw8bGUl_x_jTj3ccPDVZFD9pIuhLhBOneufuBiB4cS98l2SR_RQyGWSeWjnczT0QU91p1DhOVRuOopznQ"
};

> var n = r.b64tohex(jwk['n']);

> var d = r.b64tohex(jwk['d']);

> var e = r.b64tohex(jwk['e']);

> var jws = new r.jws.JWS();

> var signature = jws.generateJWSByNED(jwsHeader, jwsPayload, n, e, d);
TypeError: Object [object Object] has no method 'isSafeJSONString'
    at generateJWSByNED (/Users/hiyosi/code/rsa-sign/node_modules/jsrsasign/lib/jsrsasign.js:258:2624)
    at repl:1:5
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
````

**Comment by adamrogas** [comment]
This happened to me as well. It appears that at some point the isSafeJSONString method was made static, while the jws.JWS object expects it to be a member function, the easiest solution is the patch right after the static declaration 

```javascript
KJUR.jws.JWS.isSafeJSONString = function (s, h, p) {
    var o = null;
    try {
        o = jsonParse(s);
        if (typeof o != "object") return 0;
        if (o.constructor === Array) return 0;
        if (h) h[p] = o;
        return 1;
    } catch (ex) {
        return 0;
    }
};
KJUR.jws.JWS.prototype.isSafeJSONString = KJUR.jws.JWS.isSafeJSONString;
```

**Comment by kjur** [comment]
After 4.8.1, jsrsasign supports JWK in KEYUTIL.getKey method. So please use it. The 'generateJWSByNED' is deprecated method.
