### ISSUE TITLE
Feature request: Add JWK support for P-521

### ISSUE THREAD

**Issue by augjoh** [kjur/jsrsasign#525]
When trying to generate a JWK key from an ECDSA P-521 key object, an error is thrown

Sample script that demonstrates the exception:
```
$ cat test/jwk.mjs
#!/usr/bin/env node

import { KEYUTIL } from 'jsrsasign';

let kp1 = KEYUTIL.generateKeypair("EC", "P-521");
console.log(KEYUTIL.getJWKFromKey(kp1.pubKeyObj));
console.log(KEYUTIL.getJWKFromKey(kp1.prvKeyObj));
```

Exception thrown:
```
$ node test/jwk.mjs
/usr/home/node/node_modules/jsrsasign/lib/jsrsasign.js:15105
                        throw new Error("unsupported curve name for JWT: " + a)
                              ^

Error: unsupported curve name for JWT: P-521
    at Object.KEYUTIL.getJWKFromKey (/usr/home/node/node_modules/jsrsasign/lib/jsrsasign.js:15105:31)
    at file:///usr/home/node/test/jwk.mjs:6:21
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

Please add support for P-521 in KEYUTIL.getJWKfromKey()

```
@@ -15088,7 +15088,7 @@
         } else {
             if (d instanceof KJUR.crypto.ECDSA && d.isPrivate) {
                 var a = d.getShortNISTPCurveName();
-                if (a !== "P-256" && a !== "P-384" && a !== "P-521") {
+                if (a !== "P-256" && a !== "P-384") {
                     throw new Error("unsupported curve name for JWT: " + a)
                 }
                 var c = d.getPublicKeyXYHex();
@@ -15101,7 +15101,7 @@
             } else {
                 if (d instanceof KJUR.crypto.ECDSA && d.isPublic) {
                     var a = d.getShortNISTPCurveName();
-                    if (a !== "P-256" && a !== "P-384" && a !== "P-521") {
+                    if (a !== "P-256" && a !== "P-384") {
                         throw new Error("unsupported curve name for JWT: " + a)
                     }
                     var c = d.getPublicKeyXYHex();
```

**Comment by augjoh** [comment]
Another change was in `keyutil-1.0.js`'s `KEYUTIL.getKey()`:

```
@@ -14526,7 +14517,7 @@
         var j = new i({
             curve: l.crv
         });
-        var t = j.ecparams.keycharlen;
+        var t = j.ecparams.keylen / 4;
         var B = ("0000000000" + b64utohex(l.x)).slice(-t);
         var z = ("0000000000" + b64utohex(l.y)).slice(-t);
         var u = "04" + B + z;
@@ -14537,7 +14528,7 @@
         var j = new i({
             curve: l.crv
         });
-        var t = j.ecparams.keycharlen;
+        var t = j.ecparams.keylen / 4;
         var B = ("0000000000" + b64utohex(l.x)).slice(-t);
         var z = ("0000000000" + b64utohex(l.y)).slice(-t);
         var u = "04" + B + z;
```

**Comment by cplussharp** [comment]
I will prepare a PR
